### ISSUE TITLE
Help with Adding New Column to Plug-In

### ISSUE THREAD

**Issue by TheCedarPrince** [antistic/plover_cards#20]
Hi @antistic - thank you for making this plugin! I was wondering if you could help me with adding a new column to this plugin. On [my fork](https://github.com/TheCedarPrince/plover_cards), I am trying to add a column to support [automatic diagram creation of steno diagrams in Anki](https://github.com/openstenoproject/plover/wiki/Using-Anki-for-Learning-Stenography#making-your-own-deck) but I have not been able to run this plugin locally to try out these changes. Could you offer any guidance on how I could add a new custom defined column to your plugin? Thank  you! :smile:

**Comment by antistic** [comment]
You've probably done a few of these steps already, but just to make sure:

```bash
# make a copy of this repo
git clone https://github.com/antistic/plover_cards
# go into the right directory
cd plover_cards
# (make your changes here)
# rebuild the ui
python -m setup build_ui
# install into plover (make sure to uninstall any version of this you had installed before)
plover -s plover_plugins install -e .
# double check it's linked to the right directory
plover -s plover_plugins list | grep plover-cards
```

**Comment by TheCedarPrince** [comment]
Doh! I am a bit of an old Python user and didn't know that the pyproject.toml acts as a new spec file in place of a requirements.txt file. I just had to do a `python -m pip install .` to get this command `python -m setup build_ui` to work! I am going to close this issue for now and keep tinkering to see if I can get things working properly. Thank you!
