### ISSUE TITLE
dependency on `aqt` is not declared

### ISSUE THREAD

**Issue by benoit-pierre** [antistic/plover_cards#4]
```diff
 setup.cfg | 1 +
 1 file changed, 1 insertion(+)

diff --git i/setup.cfg w/setup.cfg
index 458de98..b6b8f49 100644
--- i/setup.cfg
+++ w/setup.cfg
@@ -26,6 +26,7 @@ keywords = plover plover_plugin anki
 zip_safe = True
 python_requires = >=3.7
 install_requires =
+  aqt
   plover[gui_qt]>=4.0.0.dev3
 packages =
   plover_cards
```
Which ends up pulling **a lot of stuff**, including `PyQtWebEngine`. And from a quick test, it still does not work after that:
```
 The 'PySocks!=1.5.7,>=1.5.6; extra == "socks"' distribution was not found and is required by requests
```

Another bug in pip's resolver I imagine.

**Comment by antistic** [comment]
I imagine that most of the dependencies come from `anki` and since the extension doesn't make sense without it I think it's fine.

The part where it still doesn't work is, um, slightly concerning.
